services:
  goapp:
    build: ./go-server
    container_name: goapp-svc
    expose:
      - "8080"
    volumes:
      - ./radio_data:/srv/radio
    networks:
      - webnet
    # ports:
    #   - "8080:8080"  

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - goapp-svc
    volumes:
      - ./radio_data:/srv/radio
    networks:
      - webnet

networks:
  webnet:
