name: Pull Request Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'go-server/**'
      - 'nginx/**'
      - '.github/workflows/**'
      - 'docker-compose.yaml'

jobs:
  test:
    name: Test and Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install dependencies
        run: cd go-server && go mod tidy

      - name: Run tests
        run: cd go-server && go test ./internal/hls -v

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: go-server

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Go Server Image
        uses: docker/build-push-action@v5
        with:
          context: ./go-server
          push: false
          load: true
          tags: go-server:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Nginx Image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          push: false
          load: true
          tags: nginx-server:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'go-server:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
